"""Regenerate the ARCHITECTURE.md diagrams.

    python3 tools/pd_role_switch/img/make_diagrams.py

Committed alongside the PNGs on purpose: the first versions of these were
generated by a script that was never checked in, so the only way to change a
number in a picture was to redraw it from scratch.

Palette matches the rest of the docs: indigo is the prefill role, copper the
decode role, grey is anything a switch does not touch.
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

INDIGO = "#33518F"
COPPER = "#B4661C"
INK = "#1B1D23"
MUTED = "#6B7280"
LINE = "#C9CDD4"
PANEL = "#F4F5F7"
WHITE = "#FFFFFF"

FONT = {"family": "DejaVu Sans"}


def box(ax, x, y, w, h, face=WHITE, edge=LINE, lw=1.2, r=0.012, z=2):
    ax.add_patch(
        FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=0,rounding_size=%f" % r,
            facecolor=face, edgecolor=edge, linewidth=lw, zorder=z,
        )
    )


def text(ax, x, y, s, size=11, color=INK, weight="normal", ha="left", va="center", z=4):
    ax.text(x, y, s, fontsize=size, color=color, fontweight=weight,
            ha=ha, va=va, zorder=z, **FONT)


def arrow(ax, xy1, xy2, color=MUTED, lw=1.6, style="-|>", z=3):
    ax.add_patch(
        FancyArrowPatch(xy1, xy2, arrowstyle=style, mutation_scale=14,
                        color=color, linewidth=lw, zorder=z,
                        shrinkA=2, shrinkB=2)
    )


def solution_diagram(path):
    """What we added, where it lives, and why the switch has two paths."""
    fig, ax = plt.subplots(figsize=(15.5, 9.6), dpi=140)
    ax.set_xlim(0, 100)
    ax.set_ylim(-7.0, 62)
    ax.axis("off")
    fig.patch.set_facecolor(WHITE)

    text(ax, 2, 59.5, "Changing a replica's role in place", size=18, weight="bold")
    text(ax, 2, 57.0,
         "Everything below is added by this work except where marked. One HTTP call "
         "reaches every engine core, and each rebuilds its own MoE layers.",
         size=10.5, color=MUTED)

    # ---- the call path -----------------------------------------------------
    text(ax, 2, 53.6, "THE CALL PATH", size=9.5, weight="bold", color=MUTED)

    steps = [
        (2.0, "POST /switch_pd_role", "api_router.py  ·  73 lines",
         "dev-mode route; returns ranks_switched"),
        (26.0, "AsyncLLM.switch_pd_role", "async_llm.py  ·  +83",
         "validates the requested role"),
        (50.0, "call_utility_all_async", "core_client.py  ·  +24",
         "fans out to EVERY engine core,\nnot just rank 0"),
        (74.0, "EngineCore.switch_pd_role", "pd_role.py  ·  278 lines",
         "quiesce, pause, switch, resume"),
    ]
    for x, title, where, why in steps:
        box(ax, x, 44.0, 22.0, 8.4, face=PANEL, edge=LINE)
        text(ax, x + 1.1, 50.7, title, size=11.5, weight="bold")
        text(ax, x + 1.1, 48.6, where, size=9.5, color=INDIGO, weight="bold")
        text(ax, x + 1.1, 46.3, why, size=9.5, color=MUTED, va="center")
    for x in (24.0, 48.0, 72.0):
        arrow(ax, (x, 48.2), (x + 2.0, 48.2))

    # ---- what one engine core does ----------------------------------------
    text(ax, 2, 41.0, "INSIDE ONE ENGINE CORE", size=9.5, weight="bold", color=MUTED)

    # Left: what a switch leaves alone. Right: what it changes -- placed under
    # the last call-path step, which is what descends into this section.
    box(ax, 2.0, 30.6, 44.0, 9.4, face=WHITE, edge=LINE)
    text(ax, 3.1, 38.2, "Never touched by a switch", size=11.5, weight="bold")
    text(ax, 3.1, 35.9, "model weights", size=10, color=MUTED)
    text(ax, 22.0, 35.9, "87.7 GiB/GPU — not read or moved", size=10)
    text(ax, 3.1, 34.0, "KV cache", size=10, color=MUTED)
    text(ax, 22.0, 34.0, "same layout in both roles", size=10)
    text(ax, 3.1, 32.1, "CUDA graphs", size=10, color=MUTED)
    text(ax, 22.0, 32.1, "valid wherever the old buffer can be parked", size=10)

    box(ax, 50.0, 30.6, 46.0, 9.4, face=PANEL, edge=LINE)
    text(ax, 51.1, 38.2, "pd_role.py resolves the role into three settings",
         size=11.5, weight="bold")
    text(ax, 51.1, 35.9, "scheduler token budget", size=10, color=MUTED)
    text(ax, 75.0, 35.9, "2048  ⇄  128", size=10.5, weight="bold")
    text(ax, 51.1, 34.0, "KV connector direction", size=10, color=MUTED)
    text(ax, 75.0, 34.0, "producer  ⇄  consumer", size=10.5, weight="bold")
    text(ax, 51.1, 32.1, "MoE all2all buffer", size=10, color=MUTED)
    text(ax, 75.0, 32.1, "one of the two paths below", size=10.5, weight="bold",
         color=COPPER)

    # From the last call-path step into the work it does.
    arrow(ax, (85.0, 44.0), (85.0, 40.2), color=LINE)

    # ---- the two paths -----------------------------------------------------
    text(ax, 2, 28.4, "WHY TWO PATHS  —  pd_role_switch.py  ·  867 lines",
         size=9.5, weight="bold", color=MUTED)

    # Path A
    box(ax, 2.0, 1.6, 45.0, 24.4, face=WHITE, edge=INDIGO, lw=1.8)
    text(ax, 3.2, 24.1, "PATH A  ·  the role IS the backend", size=12,
         weight="bold", color=INDIGO)
    text(ax, 3.2, 21.9, "deepep_high_throughput  ⇄  deepep_low_latency",
         size=10.5, weight="bold")
    text(ax, 3.2, 19.8,
         "Two backends, two all2all managers, two NVSHMEM\n"
         "buffers (1264 and 3226 MiB on H100). Switching means\n"
         "swapping which one the layers use.",
         size=9.5, color=MUTED, va="top")
    text(ax, 3.2, 14.2, "So the switch must:", size=9.5, weight="bold")
    text(ax, 3.2, 12.6,
         "•  check the two backends share a weight layout\n"
         "•  park the outgoing buffer, where it can",
         size=9.5, color=MUTED, va="top")
    text(ax, 3.2, 8.6,
         "Across nodes it cannot. nvshmem::init takes different team\n"
         "parameters per backend, so the two buffers cannot coexist and\n"
         "the outgoing one must be destroyed — stranding every captured\n"
         "CUDA graph. Internode Path A is eager-only: 4.9x slower decode.",
         size=9.0, color=COPPER, va="top")

    # Path B
    box(ax, 51.0, 1.6, 45.0, 24.4, face=WHITE, edge=COPPER, lw=1.8)
    text(ax, 52.2, 24.1, "PATH B  ·  one backend, both roles", size=12,
         weight="bold", color=COPPER)
    text(ax, 52.2, 21.9, "deepep_v2  →  deepep_v2", size=10.5, weight="bold")
    text(ax, 52.2, 19.8,
         "One ElasticBuffer serves both roles. The backend never\n"
         "changes; what changes is the token budget it is sized\n"
         "for — 2048 for prefill, 128 for decode.",
         size=9.5, color=MUTED, va="top")
    text(ax, 52.2, 14.2, "So the switch must:", size=9.5, weight="bold")
    text(ax, 52.2, 12.6,
         "•  size the buffer for the INCOMING role's budget\n"
         "•  reuse a parked buffer when one already fits",
         size=9.5, color=MUTED, va="top")
    text(ax, 52.2, 8.6,
         "NCCL symmetric memory lets two ElasticBuffers coexist, so\n"
         "nothing is destroyed and the graphs survive across nodes too.\n"
         "That is why Path B exists, and why every measurement in this\n"
         "document uses it.",
         size=9.0, color=COPPER, va="top")

    # The buffer line fans out into the two paths. Both start from that line so
    # neither reads as descending from the "never touched" column.
    arrow(ax, (73.0, 31.4), (24.5, 26.2), color=INDIGO, lw=1.4)
    arrow(ax, (73.0, 31.4), (73.5, 26.2), color=COPPER, lw=1.4)

    # ---- why both survive --------------------------------------------------
    box(ax, 2.0, -6.4, 94.0, 6.2, face=PANEL, edge=LINE)
    text(ax, 3.2, -2.0, "Both paths exist because vLLM still has both.",
         size=11, weight="bold")
    text(ax, 3.2, -4.4,
         "Path B supersedes Path A and is what these measurements use, but "
         "deepep_high_throughput and deepep_low_latency remain separate backends "
         "upstream, so a deployment\npinned to either still needs Path A. The two "
         "differ in what a role means — a backend, or a budget — which is why "
         "one code path cannot serve both.",
         size=9.5, color=MUTED, va="center")

    fig.savefig(path, bbox_inches="tight", facecolor=WHITE)
    plt.close(fig)
    print("wrote", path)


if __name__ == "__main__":
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    solution_diagram(os.path.join(here, "solution.png"))
